{
 "title": "Blocked Domains Dashboard",
 "tags": [
  "influxdb",
  "dns",
  "blocked"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Всего блокировок",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"block-domain\" and r._field == \"count\")\n  |> group(columns: [\"domain\"])     // 1. Сначала агрегируем по каждому домену\n  |> sum()\n  |> group(columns: [])             // 2. Снимаем группировку (все домены в одну таблицу)\n  |> sum(column: \"_value\")          // 3. Складываем все суммы в одно число\n"
    }
   ]
  },
  {
   "title": "Топ 10 доменов",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"block-domain\" and r._field == \"count\")\n  |> group(columns: [\"domain\"])     // группируем по domain\n  |> sum()                         // суммируем _value внутри каждой группы\n  |> group(columns: [])            // объединяем все группы в одну таблицу\n  |> sort(columns: [\"_value\"], desc: true)\n  |> limit(n: 10)\n  |> keep(columns: [\"domain\", \"_value\"])  // оставим только нужные колонки\n"
    }
   ]
  },
  {
   "title": "Блокировки по времени",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"events\") \n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"block-domain\" and r._field == \"count\") |> aggregateWindow(every: 5m, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Последние заблокированные домены",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"events\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"block-domain\" and r._field == \"count\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"domain\"])\n  |> limit(n: 20)\n"
    }
   ]
  }
 ]
}