// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_auth_web.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_auth_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_auth_web.StatusResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_auth_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/clients": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "List clients",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ListClientsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_clients_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/clients/change-filter": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Change client filter flag",
                "parameters": [
                    {
                        "description": "Target state",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ChangeFilterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ClientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.BadRequestResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_clients_web.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_clients_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/clients/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Create client",
                "parameters": [
                    {
                        "description": "Client to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.CreateClientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ClientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.BadRequestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_clients_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/clients/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Delete client",
                "parameters": [
                    {
                        "description": "Client id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.DeleteClientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_clients_web.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.BadRequestResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_clients_web.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_clients_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/clients/discover": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Scan LAN for devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.DiscoverResponse"
                        }
                    },
                    "409": {
                        "description": "discovery is not supported in the current deployment mode",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_clients_web.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_clients_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/clients/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Update client metadata",
                "parameters": [
                    {
                        "description": "Fields to patch",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.UpdateClientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ClientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.BadRequestResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_clients_web.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_clients_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/config/db/download": {
            "get": {
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Download database file",
                "responses": {
                    "200": {
                        "description": "filter.sqlite",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/api/config/logger/change-level": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Change log level",
                "parameters": [
                    {
                        "description": "Target log level",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.UpdateConfigData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_logger_web.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_logger_web.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/config/logger/get-level": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get log level",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.LogLevelResponse"
                        }
                    }
                }
            }
        },
        "/api/dns-records": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dns-records"
                ],
                "summary": "List blocked DNS records",
                "parameters": [
                    {
                        "description": "Pagination and filtering",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.GetAllDnsRecordsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.GetAllDnsRecordsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_blocked-domain_web.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_blocked-domain_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/dns-records/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dns-records"
                ],
                "summary": "Create a blocked DNS record",
                "parameters": [
                    {
                        "description": "Domain to block",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/create_domain.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_blocked-domain_web.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_blocked-domain_web.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_blocked-domain_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/dns-records/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dns-records"
                ],
                "summary": "Update a blocked DNS record",
                "parameters": [
                    {
                        "description": "Record id and target active state",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/update_dns_record.UpdateBlockList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.UpdateDnsRecordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_blocked-domain_web.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_blocked-domain_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/events/block/amount": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Total block events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.GetAmountResponse"
                        }
                    }
                }
            }
        },
        "/api/events/block/amount-by-group": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Block events grouped by domain",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.GetAmountByDomainResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_blocked-domain_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/filter/change-status": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filter"
                ],
                "summary": "Toggle the DNS filter",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.FilterStatusResponse"
                        }
                    }
                }
            }
        },
        "/api/filter/pause": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filter"
                ],
                "summary": "Pause the DNS filter for N minutes",
                "parameters": [
                    {
                        "description": "duration in minutes",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.PauseFilterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.FilterStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/filter/resume": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filter"
                ],
                "summary": "Resume the DNS filter (clear pause)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.FilterStatusResponse"
                        }
                    }
                }
            }
        },
        "/api/filter/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "filter"
                ],
                "summary": "Get filter status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.FilterStatusResponse"
                        }
                    }
                }
            }
        },
        "/api/sources": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "List block-list sources",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.GetAllSourcesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_source_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/sources/change-status": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sources"
                ],
                "summary": "Toggle a block-list source",
                "parameters": [
                    {
                        "description": "Source id and target active state",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ChangeSourceActiveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.ChangeSourceActiveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_source_web.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_source_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/suggest-to-block": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suggest-to-block"
                ],
                "summary": "List suggested-to-block domains",
                "parameters": [
                    {
                        "description": "Pagination and filtering",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.GetAllSuggestBlocksRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.GetAllSuggestBlocksResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_suggest-to-block_web.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_suggest-to-block_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/suggest-to-block/add-to-block": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suggest-to-block"
                ],
                "summary": "Promote suggestion to block list",
                "parameters": [
                    {
                        "description": "Suggestion id and domain",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.AddToBlockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_suggest-to-block_web.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_suggest-to-block_web.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_suggest-to-block_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/suggest-to-block/change-status": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suggest-to-block"
                ],
                "summary": "Toggle suggestion active state",
                "parameters": [
                    {
                        "description": "Suggestion id and target active state",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.ChangeSuggestStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_suggest-to-block_web.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_suggest-to-block_web.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_alextorq_dns-filter_suggest-to-block_web.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/suggest-to-block/codes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suggest-to-block"
                ],
                "summary": "List reason codes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.GetSignalCodesResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "collect.SignalDescriptor": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "create_domain.RequestBody": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "db.BlockDomainEvent": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "domainId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "db.BlockList": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "blocked-events": {
                    "description": "One-to-Many",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.BlockDomainEvent"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "db.BlockListSource": {
            "type": "string",
            "enum": [
                "StevenBlack",
                "EasyList",
                "RuAdList",
                "AdGuardRussian",
                "HaGeZiMulti",
                "User",
                "SuggestedToBlock"
            ],
            "x-enum-varnames": [
                "SourceStevenBlack",
                "SourceEasyList",
                "SourceRuAdList",
                "SourceAdGuardRussian",
                "SourceHaGeZiMulti",
                "SourceUser",
                "SourceSuggestedToBlock"
            ]
        },
        "db.Client": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "filtered": {
                    "type": "boolean"
                },
                "hostname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "last_seen": {
                    "type": "string"
                },
                "mac": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                }
            }
        },
        "db.DomainCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "domain": {
                    "type": "string"
                }
            }
        },
        "db.Source": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "$ref": "#/definitions/db.BlockListSource"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "db.SuggestBlock": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "domain": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reasons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.SuggestBlockReason"
                    }
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "db.SuggestBlockReason": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "match": {
                    "type": "string"
                }
            }
        },
        "discovery.Device": {
            "type": "object",
            "properties": {
                "already_registered": {
                    "type": "boolean"
                },
                "hostname": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "mac": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                }
            }
        },
        "github_com_alextorq_dns-filter_auth_web.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_alextorq_dns-filter_auth_web.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_alextorq_dns-filter_blocked-domain_web.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_alextorq_dns-filter_blocked-domain_web.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_alextorq_dns-filter_clients_web.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_alextorq_dns-filter_clients_web.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_alextorq_dns-filter_logger_web.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_alextorq_dns-filter_source_web.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_alextorq_dns-filter_suggest-to-block_web.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_alextorq_dns-filter_suggest-to-block_web.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "update_dns_record.UpdateBlockList": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "web.AddToBlockRequest": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "web.BadRequestResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "web.ChangeFilterRequest": {
            "type": "object",
            "properties": {
                "filtered": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "web.ChangeSourceActiveRequest": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "web.ChangeSourceActiveResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "record": {
                    "$ref": "#/definitions/db.Source"
                }
            }
        },
        "web.ChangeSuggestStatusRequest": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "web.ClientResponse": {
            "type": "object",
            "properties": {
                "client": {
                    "$ref": "#/definitions/db.Client"
                }
            }
        },
        "web.CreateClientRequest": {
            "type": "object",
            "properties": {
                "filtered": {
                    "type": "boolean"
                },
                "hostname": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "mac": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                }
            }
        },
        "web.DeleteClientRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "web.DiscoverResponse": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/discovery.Device"
                    }
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "web.FilterStatusResponse": {
            "type": "object",
            "properties": {
                "paused_until": {
                    "description": "PausedUntil is the unix-second deadline of an active pause, or 0 if no\npause is active. The frontend uses this absolute value to drive its\ncountdown without depending on server-supplied \"seconds left\".",
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "web.GetAllDnsRecordsRequest": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "web.GetAllDnsRecordsResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.BlockList"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "web.GetAllSourcesResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.Source"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "web.GetAllSuggestBlocksRequest": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "codes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "filter": {
                    "type": "string"
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "web.GetAllSuggestBlocksResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.SuggestBlock"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "web.GetAmountByDomainResponse": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.DomainCount"
                    }
                }
            }
        },
        "web.GetAmountResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                }
            }
        },
        "web.GetSignalCodesResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/collect.SignalDescriptor"
                    }
                }
            }
        },
        "web.ListClientsResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.Client"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "web.LogLevelResponse": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                }
            }
        },
        "web.LoginRequest": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "web.PauseFilterRequest": {
            "type": "object",
            "properties": {
                "minutes": {
                    "type": "integer"
                }
            }
        },
        "web.UpdateClientRequest": {
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                }
            }
        },
        "web.UpdateConfigData": {
            "type": "object",
            "properties": {
                "logLevel": {
                    "type": "string"
                }
            }
        },
        "web.UpdateDnsRecordResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "record": {
                    "$ref": "#/definitions/db.BlockList"
                }
            }
        },
        "web.UserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "DNS Filter API",
	Description:      "HTTP API for the DNS filter: managing block lists, sources, clients, suggestions and runtime config.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
